# Generated by Django 5.2.6 on 2025-09-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coment',
            new_name='Comment',
        ),
    ]
